name: sync_room
description: App de salas sincronizadas para assistir e navegar junto.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  flutter_webrtc: ^0.11.7
  webview_flutter: ^4.8.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
